eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    timeout: 30s

server:
  port: 8805