spring:
  application:
    name: im-service
  jackson:
    default-property-inclusion: non_null  #如果值为null,构造json时不加入
    date-format: yyyy-MM-dd HH:mm    #指定Json中Date对象的传输格式.对于DTO还是使用以往的方式
    locale: zh_CN
    time-zone: Asia/Shanghai
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  pub-key-file-name: RSA.pub
