# zuul不支持websocket，所以用spring-cloud-gateway代替
spring:
  application:
    name: cloud-gateway
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

      - id: auth
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**

      - id: chat
        uri: lb://IM-SERVICE
        predicates:
        - Path=/chat/**
      - id: ws
        uri: lb:ws://IM-SERVICE #websocket
        predicates:
        - Path=/ws/**

      - id: index
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/index/**
      - id: goods
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/goods/**
      - id: catalog
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/catalog/**
      - id: catalog
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/catalog/**
      - id: search
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/search/**
      - id: post
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/post/**
      - id: goodsUser
        uri: lb://GOODS-SERVICE
        predicates:
        - Path=/goodsUser/**

logging:
  level:
    org.springframework.cloud.gateway: debug